---
version: "2"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/docker/sonarr/config:/config
      - smb-tv:/tv
      - local-downloads:/downloads
    ports:
      - 8989:8989
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/docker/radarr/config:/config
      - smb-movies:/movies
      - local-downloads:/downloads
    ports:
      - 7878:7878
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/docker/sabnzbd/config:/config
      - local-scratch:/incomplete-downloads
      - local-downloads:/downloads
    ports:
      - 8080:8080
      - 9090:9090
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qBT
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8082
    volumes:
      - /home/pi/docker/qbittorrent/config:/config
      - local-downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8082:8082
  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/docker/jackett/config:/config
      - local-scratch:/downloads
    ports:
      - 9117:9117
  nzbhydra:
    image: ghcr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/docker/nzbhydra/config:/config
      - local-scratch:/downloads
    ports:
      - 5076:5076
  requestrr:
    image: darkalfx/requestrr
    container_name: requestrr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/docker/requestrr/config:/root/config
    ports:
      - 4545:4545
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/docker/ombi/config:/config
    ports:
      - 3579:3579
volumes:
  smb-tv:
    external: true
  smb-movies:
    external: true
  local-downloads:
    external: true
  local-scratch:
    external: true